// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeShare.Web.Data.Models;

public partial class Recipe
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public string Ingredients { get; set; }

    public string Steps { get; set; }

    public int CookingTime { get; set; }

    public string DietaryTags { get; set; }

    public string UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<RecipeFavourite> RecipeFavourites { get; set; } = new List<RecipeFavourite>();

    public virtual AspNetUser User { get; set; }
}