// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeShare.Web.Data.Models;

public partial class RecipeStep
{
    public long Id { get; set; }

    public long RecipeId { get; set; }

    public int StepNumber { get; set; }

    public string Instruction { get; set; }

    public virtual Recipe Recipe { get; set; }
}