// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeShare.Web.Data.Models;

public partial class UserProfile
{
    public long Id { get; set; }

    public string UserId { get; set; }

    public string DisplayName { get; set; }

    public string Bio { get; set; }

    public string ProfileImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual AspNetUser User { get; set; }
}