// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeShare.API.Data.Models;

public partial class RecipeFavourite
{
    public long Id { get; set; }

    public long RecipeId { get; set; }

    public string UserId { get; set; }

    public virtual Recipe Recipe { get; set; }
}