// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeShare.API.Data.Models;

public partial class RecipeImage
{
    public long Id { get; set; }

    public long RecipeId { get; set; }

    public string ImageUrl { get; set; }

    public bool IsCover { get; set; }

    public string Caption { get; set; }

    public int DisplayOrder { get; set; }

    public virtual Recipe Recipe { get; set; }
}